In [1]:
import numpy as np

In [2]:
B = np.array([
    [1, 1, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 1, 0, 0, 1],
    [0, 0, 1, 1, 1],
])

In [3]:
B @ B.T

array([[3, 1, 1, 1],
       [1, 2, 0, 1],
       [1, 0, 2, 1],
       [1, 1, 1, 3]])

In [4]:
B.T @ B

array([[2, 1, 1, 1, 0],
       [1, 2, 1, 0, 1],
       [1, 1, 2, 1, 1],
       [1, 0, 1, 2, 1],
       [0, 1, 1, 1, 2]])

## Adjacency Matrix

In [9]:
M = np.array([
    [0, 1, 1, 1, 0],
    [1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 1, 0],
])

## Degree Matrix

In [10]:
D = np.diag(M @ np.ones(5))
print(D)

[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


## Random Walk Matrix

In [12]:
W = M @ np.linalg.inv(D)
print(W)

[[0.         0.33333333 0.25       0.33333333 0.        ]
 [0.33333333 0.         0.25       0.         0.33333333]
 [0.33333333 0.33333333 0.         0.33333333 0.33333333]
 [0.33333333 0.         0.25       0.         0.33333333]
 [0.         0.33333333 0.25       0.33333333 0.        ]]


In [20]:
D2 = np.sqrt(np.array([3, 3, 4, 3, 3]))
D2inv = np.diag(1 / D2)
D2 = np.diag(D2)

In [21]:
print(D2inv @ W @ D2)

[[0.         0.33333333 0.28867513 0.33333333 0.        ]
 [0.33333333 0.         0.28867513 0.         0.33333333]
 [0.28867513 0.28867513 0.         0.28867513 0.28867513]
 [0.33333333 0.         0.28867513 0.         0.33333333]
 [0.         0.33333333 0.28867513 0.33333333 0.        ]]


In [22]:
print(D2inv @ M @ D2inv)

[[0.         0.33333333 0.28867513 0.33333333 0.        ]
 [0.33333333 0.         0.28867513 0.         0.33333333]
 [0.28867513 0.28867513 0.         0.28867513 0.28867513]
 [0.33333333 0.         0.28867513 0.         0.33333333]
 [0.         0.33333333 0.28867513 0.33333333 0.        ]]
